language: php

php:
  - 7.0

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer install

script:
  - vendor/bin/codecept run unit --coverage-xml
  - vendor/bin/codecept run unit

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover tests/_log/coverage.xml

notifications:
  irc: "irc.freenode.org#fuelphp-status"
