language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer install

script: phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover 
 
notifications:
  irc: "irc.freenode.org#fuelphp-status"
